In [3]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
print (sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic', 'anagrams', 'anagrams', 'anscombe', 'anscombe', 'attention', 'attention', 'brain_networks', 'brain_networks', 'car_crashes', 'car_crashes', 'diamonds', 'diamonds', 'dots', 'dots', 'dowjones', 'dowjones', 'exercise', 'exercise', 'flights', 'flights', 'fmri', 'fmri', 'geyser', 'geyser', 'glue', 'glue', 'healthexp', 'healthexp', 'iris', 'iris', 'mpg', 'mpg', 'penguins', 'penguins', 'planets', 'planets', 'seaice', 'seaice', 'taxis', 'taxis', 'tips', 'tips', 'titanic', 'titanic', 'anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [20]:
data = pd.read_excel("Cardiac_Outcomes.xlsx",
sheet_name=['Hospitalization_Discharge','CardiacComplications','Responsivenes','PatientHistory','Labs','Demography','Patient_Precriptions'])

In [31]:
data

{'Hospitalization_Discharge':       inpatient_number DestinationDischarge admission_ward admission_way  \
 0               857781                 Home     Cardiology  NonEmergency
 1               743087                 Home     Cardiology  NonEmergency
 2               866418                 Home     Cardiology  NonEmergency
 3               775928                 Home     Cardiology     Emergency
 4               810128                 Home     Cardiology  NonEmergency
 ...                ...                  ...            ...           ...
 2003            740689   HealthcareFacility    GeneralWard     Emergency
 2004            734280   HealthcareFacility    GeneralWard     Emergency
 2005            781004   HealthcareFacility     Cardiology     Emergency
 2006            744870              Unknown     Cardiology  NonEmergency
 2007            791864                 Home     Cardiology     Emergency

      discharge_department  visit_times respiratory_support oxygen_inhalation  \
 0              Cardiology            1                 NaN     OxygenTherapy
 1              Cardiology            1                 NaN     OxygenTherapy
 2              Cardiology            2                 NaN     OxygenTherapy
 3              Cardiology            1                 NaN     OxygenTherapy
 4              Cardiology            1                 NaN     OxygenTherapy
 ...                   ...          ...                 ...               ...
 2003          GeneralWard            1                 NaN     OxygenTherapy
 2004          GeneralWard            1                 NaN     OxygenTherapy
 2005           Cardiology            1                 NaN     OxygenTherapy
 2006           Cardiology            1                 IMV     OxygenTherapy
 2007           Cardiology            1                 NaN     OxygenTherapy

       dischargeDay Admission_date  ... death_within_28_days  \
 0               11     2017-01-24  ...                    0
 1                8     2017-05-05  ...                    0
 2                5     2016-11-18  ...                    0
 3               11     2017-10-02  ...                    0
 4                5     2019-11-17  ...                    0
 ...            ...            ...  ...                  ...
 2003             5     2016-02-07  ...                    0
 2004             8     2017-03-29  ...                    0
 2005            14     2018-01-22  ...                    0
 2006             1     2019-11-27  ...                    1
 2007             6     2017-02-17  ...                    0

       re_admission_within_28_days  death_within_3_months  \
 0                               0                      0
 1                               0                      0
 2                               0                      0
 3                               1                      0
 4                               0                      0
 ...                           ...                    ...
 2003                            0                      0
 2004                            0                      0
 2005                            0                      0
 2006                            0                      1
 2007                            0                      0

       re_admission_within_3_months  death_within_6_months  \
 0                                0                      0
 1                                0                      0
 2                                0                      0
 3                                1                      0
 4                                0                      0
 ...                            ...                    ...
 2003                             0                      0
 2004                             0                      0
 2005                             1                      0
 2006                             0                      1
 2007                             0                      0

       re_admission_within_6_months  time_of_death__days_from_admission  \
 0                                0                                 NaN
 1                                0                                 NaN
 2                                0                                 NaN
 3                                1                                 NaN
 4                                0                                 NaN
 ...                            ...                                 ...
 2003                             0                                 NaN
 2004                             0                                 NaN
 2005                             1                                 NaN
 2006                             0                                 1.0
 2007                             0                                 NaN

       readmission_time_days_from_admission  \
 0                                      NaN
 1                                      NaN
 2                                      NaN
 3                                     19.0
 4                                      NaN
 ...                                    ...
 2003                                   NaN
 2004                                   NaN
 2005                                  76.0
 2006                                   NaN
 2007                                   NaN

       return_to_emergency_department_within_6_months  \
 0                                                0.0
 1                                                0.0
 2                                                0.0
 3                                                1.0
 4                                                0.0
 ...                                              ...
 2003                                             0.0
 2004                                             0.0
 2005                                             1.0
 2006                                             0.0
 2007                                             0.0

       time_to_emergency_department_within_6_months
 0                                              NaN
 1                                              NaN
 2                                              NaN
 3                                             19.0
 4                                              NaN
 ...                                            ...
 2003                                           NaN
 2004                                           NaN
 2005                                          76.0
 2006                                           NaN
 2007                                           NaN

 [2008 rows x 21 columns],
 'CardiacComplications':       inpatient_number  NYHA_cardiac_function_classification  Killip_grade  \
 0               857781                                     3             3
 1               743087                                     3             1
 2               866418                                     2             2
 3               775928                                     3             2
 4               810128                                     3             2
 ...                ...                                   ...           ...
 2003            740689                                     4             1
 2004            734280                                     4             2
 2005            781004                                     3             1
 2006            744870                                     4             4
 2007            791864                                     3             1

       myocardial_infarction  congestive_heart_failure  \
 0                         0                         0
 1                         0                         0
 2                         0                         0
 3                         0                         0
 4                         0                         0
 ...                     ...                       ...
 2003                      0                         1
 2004                      0                         1
 2005                      0                         1
 2006                      0                         1
 2007                      0                         1

       peripheral_vascular_disease type_of_heart_failure  LVEF  \
 0                               0                  Both   NaN
 1                               0                  Both   NaN
 2                               0                  Both   NaN
 3                               0                  Both   NaN
 4                               0                  Both   NaN
 ...                           ...                   ...   ...
 2003                            0                  Both   NaN
 2004                            0                  Both   NaN
 2005                            0                  Both   NaN
 2006                            0                  Both   NaN
 2007                            0                  Left   NaN

       left_ventricular_end_diastolic_diameter_LV  mitral_valve_EMS  \
 0                                            NaN               NaN
 1                                           40.0              1.16
 2                                           46.0              0.84
 3                                            NaN               NaN
 4                                           64.0              1.20
 ...                                          ...               ...
 2003                                         NaN               NaN
 2004                                         NaN               NaN
 2005                                         NaN               NaN
 2006                                         NaN               NaN
 2007                                         NaN               NaN

       mitral_valve_AMS    EA  tricuspid_valve_return_velocity  \
 0                  NaN   NaN                              NaN
 1                 1.52   NaN                             3.34
 2                 0.12  7.00                             2.80
 3                  NaN   NaN                              NaN
 4                 0.90  1.33                              NaN
 ...                ...   ...                              ...
 2003               NaN   NaN                              NaN
 2004               NaN   NaN                             2.78
 2005               NaN   NaN                              NaN
 2006               NaN   NaN                              NaN
 2007               NaN   NaN                              NaN

       tricuspid_valve_return_pressure
 0                                 NaN
 1                                47.0
 2                                32.0
 3                                 NaN
 4                                 NaN
 ...                               ...
 2003                              NaN
 2004                              NaN
 2005                              NaN
 2006                              NaN
 2007                              NaN

 [2008 rows x 14 columns],
 'Responsivenes':       inpatient_number  eye_opening  verbal_response  movement  consciousness  \
 0               857781            4                5         6          Clear
 1               743087            4                5         6          Clear
 2               866418            4                5         6          Clear
 3               775928            4                5         6          Clear
 4               810128            4                5         6          Clear
 ...                ...          ...              ...       ...            ...
 2003            740689            4                5         6          Clear
 2004            734280            4                5         6          Clear
 2005            781004            4                5         6          Clear
 2006            744870            1                1         1  Nonresponsive
 2007            791864            4                5         6          Clear

       GCS
 0      15
 1      15
 2      15
 3      15
 4      15
 ...   ...
 2003   15
 2004   15
 2005   15
 2006    3
 2007   15

 [2008 rows x 6 columns],
 'PatientHistory':       inpatient_number  cerebrovascular_disease  dementia  \
 0               857781                        0         0
 1               743087                        0         0
 2               866418                        0         0
 3               775928                        0         0
 4               810128                        0         0
 ...                ...                      ...       ...
 2003            740689                        0         0
 2004            734280                        0         0
 2005            781004                        0         0
 2006            744870                        0         0
 2007            791864                        0         0

       Chronic_obstructive_pulmonary_disease  connective_tissue_disease  \
 0                                         1                          0
 1                                         0                          0
 2                                         0                          0
 3                                         1                          0
 4                                         0                          0
 ...                                     ...                        ...
 2003                                      0                          0
 2004                                      0                          0
 2005                                      0                          0
 2006                                      0                          0
 2007                                      0                          0

       peptic_ulcer_disease  diabetes  \
 0                      0.0         1
 1                      0.0         0
 2                      0.0         0
 3                      0.0         0
 4                      0.0         0
 ...                    ...       ...
 2003                   0.0         0
 2004                   0.0         0
 2005                   0.0         1
 2006                   0.0         0
 2007                   0.0         0

       moderate_to_severe_chronic_kidney_disease  hemiplegia  leukemia  \
 0                                           0.0           0         0
 1                                           0.0           0         0
 2                                           0.0           0         0
 3                                           1.0           0         0
 4                                           0.0           0         0
 ...                                         ...         ...       ...
 2003                                        1.0           0         0
 2004                                        0.0           0         0
 2005                                        0.0           0         0
 2006                                        1.0           0         0
 2007                                        1.0           0         0

       malignant_lymphoma  solid_tumor  liver_disease  AIDS  CCI_score  \
 0                      0            0            0.0     0        2.0
 1                      0            0            0.0     0        0.0
 2                      0            0            0.0     0        0.0
 3                      0            0            0.0     0        2.0
 4                      0            0            0.0     0        0.0
 ...                  ...          ...            ...   ...        ...
 2003                   0            0            0.0     0        2.0
 2004                   0            0            0.0     0        1.0
 2005                   0            0            0.0     0        2.0
 2006                   0            0            0.0     0        2.0
 2007                   0            0            0.0     0        2.0

      type_II_respiratory_failure  acute_renal_failure
 0                      NonTypeII                    0
 1                      NonTypeII                    0
 2                      NonTypeII                    0
 3                      NonTypeII                    0
 4                      NonTypeII                    0
 ...                          ...                  ...
 2003                   NonTypeII                    0
 2004                   NonTypeII                    0
 2005                   NonTypeII                    0
 2006                   NonTypeII                    0
 2007                   NonTypeII                    0

 [2008 rows x 17 columns],
 'Labs':       inpatient_number  body_temperature  pulse  respiration  \
 0               857781              36.7     87           19
 1               743087              36.8     95           18
 2               866418              36.5     98           18
 3               775928              36.0     73           19
 4               810128              35.0     88           19
 ...                ...               ...    ...          ...
 2003            740689              36.1    117           22
 2004            734280              36.3     70           21
 2005            781004              36.8    113           19
 2006            744870              36.4    134           19
 2007            791864              36.3    100           19

       systolic_blood_pressure  diastolic_blood_pressure         map  fio2  \
 0                         102                        64   76.666667    33
 1                         150                        70   96.666667    33
 2                         102                        67   78.666667    33
 3                         110                        74   86.000000    33
 4                         134                        62   86.000000    33
 ...                       ...                       ...         ...   ...
 2003                      120                        80   93.333333    33
 2004                      120                        86   97.333333    29
 2005                      135                       100  111.666667    33
 2006                       92                        72   78.666667    41
 2007                      142                        80  100.666667    33

       creatinine_enzymatic_method   urea  ...  measured_residual_base  \
 0                           108.3  12.55  ...                    -2.1
 1                            62.0   4.29  ...                     NaN
 2                           185.1  15.99  ...                     NaN
 3                           104.8   8.16  ...                     NaN
 4                            83.9   6.86  ...                     NaN
 ...                           ...    ...  ...                     ...
 2003                        115.3   8.72  ...                     NaN
 2004                         63.1   5.96  ...                     NaN
 2005                         51.9   4.27  ...                     NaN
 2006                        191.1  35.87  ...                    -2.5
 2007                        104.0   9.26  ...                     NaN

       measured_bicarbonate  carboxyhemoglobin  body_temperature_blood_gas  \
 0                     21.2                0.4                        37.0
 1                      NaN                NaN                         NaN
 2                      NaN                NaN                         NaN
 3                      NaN                NaN                         NaN
 4                      NaN                NaN                         NaN
 ...                    ...                ...                         ...
 2003                   NaN                NaN                         NaN
 2004                   NaN                NaN                         NaN

In [35]:
sheet5_df=data['Labs']
#locate the sheet
wbc=sheet5_df.loc[:,['white_blood_cell']]
print(wbc)

      white_blood_cell
0                 9.43
1                 5.32
2                13.01
3                 2.18
4                 6.14
...                ...
2003              4.04
2004              4.58
2005              5.39
2006              9.70
2007              5.34

[2008 rows x 1 columns]